name: Android CI

on: 
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      env: # Or as an environment variable
        ITAD_CLIENT_ID: ${{ secrets.ITAD_CLIENT_ID }}
        ITAD_API_KEY: ${{ secrets.ITAD_API_KEY }}
        ITAD_CLIENT_SECRET: ${{ secrets.ITAD_CLIENT_SECRET }}
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDebug -PITAD_CLIENT_ID=$ITAD_CLIENT_ID -PITAD_API_KEY=$ITAD_API_KEY -PITAD_CLIENT_SECRET=$ITAD_CLIENT_SECRET
    - name: Run detekt
      run: ./gradlew detekt
    - name: Run unit tests
      run: ./gradlew testDebug --stacktrace
      
